// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cdu4rte

//@version=5
indicator(title = "Patrones", overlay = true)

import cdu4rte/camdPattern/40
import cdu4rte/camdCONST/9

const string MA_GROUP = "Media Móvil"
const string RSI_GROUP = "RSI"
const string PATTERN_GROUP = "Patrón"

// Parámetro de entrada para habilitar/deshabilitar funcionalidades desde el entorno gráfico
bool showEMA14 = input(defval = true, title =  "EMA 14", group = MA_GROUP)
bool showEMA20 = input(defval = true, title =  "EMA 20", group = MA_GROUP)
bool showEMA50 = input(defval = true, title =  "EMA 50", group = MA_GROUP)
bool showEMA200 = input(defval = true, title =  "EMA 200", group = MA_GROUP)
bool showBarNearToEMA14 = input(defval = false, title =  "Vela cerca de la EMA de 14")
bool showMaxCloseRSI = input(defval = true, title =  "Máximo histórico sin sobre compra", group = RSI_GROUP)
bool showMinCloseRSI = input(defval = true, title =  "Mínimo histórico sin sobre compra" ,group = RSI_GROUP)

bool showPattern = input(defval = true, title =  "Mostrar patrones", group = PATTERN_GROUP)
bool showBullishPattern = input(defval = true, title =  "Mostrar patrones alcistas", group = PATTERN_GROUP)
bool showBearishPattern = input(defval = true, title =  "Mostrar patrones bajistas", group = PATTERN_GROUP)
bool showHammer = input(defval = true, title =  camdCONST.getPatternHammer(), group = PATTERN_GROUP)
bool showDojiStar = input(defval = true, title =  camdCONST.getPatternDojiStar(), group = PATTERN_GROUP)
bool showDragonflyDoji = input(defval = true, title =  camdCONST.getPatternDragonflyDoji(), group = PATTERN_GROUP)
bool showLongLeggedDoji = input(defval = true, title =  camdCONST.getPatternLongleggedDoji(), group = PATTERN_GROUP)
bool showGravestoneDoji = input(defval = true, title =  camdCONST.getPatternGravestoneDoji(), group = PATTERN_GROUP)
bool showThreeIdenticalBlackCrows = input(defval = true, title =  camdCONST.getPatternThreeIdenticalBlackCrows(), group = PATTERN_GROUP)
bool showAdvanceBlock = input(defval = true, title =  camdCONST.getPatternAdvanceBlock(), group = PATTERN_GROUP)
bool showDeliberation = input(defval = true, title =  camdCONST.getPatternDeliberation(), group = PATTERN_GROUP)
bool showUniqueThreeRiversBottom = input(defval = true, title =  camdCONST.getPatternUniqueThreeRiversBottom(), group = PATTERN_GROUP)
bool showThreeStarsInTheSouth = input(defval = true, title =  camdCONST.getPatternThreeStarsInSouth(), group = PATTERN_GROUP)
bool showBullishBreakaway = input(defval = true, title =  camdCONST.getPatternBullishBreakaway(), group = PATTERN_GROUP)
bool showBearishBreakaway = input(defval = true, title =  camdCONST.getPatternBearishBreakaway(), group = PATTERN_GROUP)
bool showConcealingBabySwallow = input(defval = true, title =  camdCONST.getPatternConcealingBabySwallow(), group = PATTERN_GROUP)
bool showStickSandwich = input(defval = true, title =  camdCONST.getPatternStickSandwich(), group = PATTERN_GROUP)
bool showMatchingLow = input(defval = true, title =  camdCONST.getPatternMatchingLow(), group = PATTERN_GROUP)
bool showLadderBottom = input(defval = true, title =  camdCONST.getPatternLadderBottom(), group = PATTERN_GROUP)
bool showThrustingLine = input(defval = true, title =  camdCONST.getPatternThrustingLine(), group = PATTERN_GROUP)
bool showInNeck = input(defval = true, title =  camdCONST.getPatternInNeck(), group = PATTERN_GROUP)
bool showOnNeck = input(defval = true, title =  camdCONST.getPatternOnNeck(), group = PATTERN_GROUP)
bool showBullishSeparatingLines = input(defval = true, title =  camdCONST.getPatternBullishSeparatingLines(), group = PATTERN_GROUP)
bool showBearishSeparatingLines = input(defval = true, title =  camdCONST.getPatternBearishSeparatingLines(), group = PATTERN_GROUP)
bool showRisingThreeMethods = input(defval = true, title =  camdCONST.getPatternRisingThreeMethods(), group = PATTERN_GROUP)
bool showFallingThreeMethods = input(defval = true, title =  camdCONST.getPatternFallingThreeMethods(), group = PATTERN_GROUP)
bool showInvertedHammer = input(defval = true, title =  camdCONST.getPatternInvertedHammer(), group = PATTERN_GROUP)
bool showHangingMan = input(defval = true, title =  camdCONST.getPatternHangingMan(), group = PATTERN_GROUP)
bool showShootingStar = input(defval = true, title =  camdCONST.getPatternShootingStar(), group = PATTERN_GROUP)
bool showBullishBeltHoldLine = input(defval = true, title =  camdCONST.getPatternBullishBeltHoldLine(), group = PATTERN_GROUP)
bool showBearishBeltHoldLine = input(defval = true, title =  camdCONST.getPatternBearishBeltHoldLine(), group = PATTERN_GROUP)
bool showBullishEngulfing = input(defval = true, title =  camdCONST.getPatternBullishEngulfing(), group = PATTERN_GROUP)
bool showBearishEngulfing = input(defval = true, title =  camdCONST.getPatternBearishEngulfing(), group = PATTERN_GROUP)
bool showBullishHarami = input(defval = true, title =  camdCONST.getPatternBullishHarami(), group = PATTERN_GROUP)
bool showBearishHarami = input(defval = true, title =  camdCONST.getPatternBearishHarami(), group = PATTERN_GROUP)
bool showHomingPigeon = input(defval = true, title =  camdCONST.getPatternHomingPigeon(), group = PATTERN_GROUP)
bool showBullishCounterAttackLine = input(defval = true, title =  camdCONST.getPatternBullishCounterAttackLine(), group = PATTERN_GROUP)
bool showBearishCounterAttackLine = input(defval = true, title =  camdCONST.getPatternBearishCounterAttackLine(), group = PATTERN_GROUP)
bool showThreeWhiteSoldiers = input(defval = true, title =  camdCONST.getPatternThreeWhiteSoldiers(), group = PATTERN_GROUP)
bool showThreeBlackCrows = input(defval = true, title =  camdCONST.getPatternThreeBlackCrows(), group = PATTERN_GROUP)
bool showMatHoldBullish = input(defval = true, title =  camdCONST.getPatternMatHoldBullish(), group = PATTERN_GROUP)
bool showBullishThreeLineStrike = input(defval = true, title =  camdCONST.getPatternBullishThreeLineStrike(), group = PATTERN_GROUP)
bool showBearishThreeLineStrike = input(defval = true, title =  camdCONST.getPatternBearishThreeLineStrike(), group = PATTERN_GROUP)
bool showBullishDojiStar = input(defval = true, title =  camdCONST.getPatternBullishDojiStar(), group = PATTERN_GROUP)
bool showBearishDojiStar = input(defval = true, title =  camdCONST.getPatternBearishDojiStar(), group = PATTERN_GROUP)
bool showMorningStar = input(defval = true, title =  camdCONST.getPatternMorningStar(), group = PATTERN_GROUP)
bool showEveningStar = input(defval = true, title =  camdCONST.getPatternEveningStar(), group = PATTERN_GROUP)
bool showMorningDojiStar = input(defval = true, title =  camdCONST.getPatternMorningDojiStar(), group = PATTERN_GROUP)
bool showEveningDojiStar = input(defval = true, title =  camdCONST.getPatternEveningDojiStar(), group = PATTERN_GROUP)
bool showBullishAbandonedBaby = input(defval = true, title =  camdCONST.getPatternBullishAbandonedBaby(), group = PATTERN_GROUP)
bool showBearishAbandonedBaby = input(defval = true, title =  camdCONST.getPatternBearishAbandonedBaby(), group = PATTERN_GROUP)
bool showBullishTriStar = input(defval = true, title =  camdCONST.getPatternBullishTriStar(), group = PATTERN_GROUP)
bool showBearishTriStar = input(defval = true, title =  camdCONST.getPatternBearishTriStar(), group = PATTERN_GROUP)
bool showUpsideGapTwoCrows = input(defval = true, title =  camdCONST.getPatternUpsideGapTwoCrows(), group = PATTERN_GROUP)
bool showTwoCrows = input(defval = true, title =  camdCONST.getPatternTwoCrows(), group = PATTERN_GROUP)
bool showUpsideTasukiGap = input(defval = true, title =  camdCONST.getPatternUpsideTasukiGap(), group = PATTERN_GROUP)
bool showDownsideTasukiGap = input(defval = true, title =  camdCONST.getPatternDownsideTasukiGap(), group = PATTERN_GROUP)
bool showUpsideGapThreeMethods = input(defval = true, title =  camdCONST.getPatternUpsideGapThreeMethods(), group = PATTERN_GROUP)
bool showDownsideGapThreeMethods = input(defval = true, title =  camdCONST.getPatternDownsideGapThreeMethods(), group = PATTERN_GROUP)
bool showUpsideGappingSideBySideWhiteLines = input(defval = true, title =  camdCONST.getPatternUpsideGappingSideBySideWhiteLines(), group = PATTERN_GROUP)
bool showDownsideGappingSideBySideWhiteLines = input(defval = true, title =  camdCONST.getPatternDownsideGappingSideBySideWhiteLines(), group = PATTERN_GROUP)
bool showBullishKicking = input(defval = true, title =  camdCONST.getPatternBullishKicking(), group = PATTERN_GROUP)
bool showBearishKicking = input(defval = true, title =  camdCONST.getPatternBearishKicking(), group = PATTERN_GROUP)

// Contadores
var int dojiStarCounter = 0
var int dragonflyDojiCounter = 0
var int longleggedDojiCounter = 0
var int gravestoneDojiCounter = 0
var int hammerCounter = 0
var int invertedHamerCounter = 0
var int hangingManCounter = 0
var int shootingStarCounter = 0
var int bullishBeltHoldLineCounter = 0
var int bearishBeltHoldLineCounter = 0
var int bullishEngulfingCounter = 0
var int bearishEngulfingCounter = 0
var int bullishHaramiCounter = 0
var int bearishHaramiCounter = 0
var int homingPigeonCounter = 0
var int threeIdenticalBlackCrowsCounter = 0
var int bullishCounterAttackLineCounter = 0
var int bearishCounterAttackLineCounter = 0
var int threeWhiteSoldiersCounter = 0
var int threeBlackCrowsCounter = 0
var int advanceBlockCounter = 0
var int deliberationCounter = 0
var int uniqueThreeRiversBottomCounter = 0
var int threeStarsInTheSouthCounter = 0
var int bullishBreakawayCounter = 0
var int bearishBreakawayCounter = 0
var int concealingBabySwallowCounter = 0
var int stickSandwichCounter = 0
var int matchingLowCounter = 0
var int ladderBottomCounter = 0
var int thrustingLineCounter = 0
var int inNeckCounter = 0
var int onNeckCounter = 0
var int bullishSeparatingLinesCounter = 0
var int bearishSeparatingLinesCounter = 0
var int risingThreeMethodsCounter = 0
var int fallingThreeMethodsCounter = 0
var int matHoldBullishCounter = 0
var int bullishThreeLineStrikeCounter = 0
var int bearishThreeLineStrikeCounter = 0
var int bullishDojiStarCounter = 0
var int bearishDojiStarCounter = 0
var int morningStarCounter = 0
var int eveningStarCounter = 0
var int morningDojiStarCounter = 0
var int eveningDojiStarCounter = 0
var int bullishAbandonedBabyCounter = 0
var int bearishAbandonedBabyCounter = 0
var int bullishTriStarCounter = 0
var int bearishTriStarCounter = 0
var int upsideGapTwoCrowsCounter  = 0
var int twoCrowsCounter = 0
var int upsideTasukiGapCounter = 0
var int downsideTasukiGapCounter = 0
var int upsideGapThreeMethodsCounter = 0
var int downsideGapThreeMethodsCounter = 0
var int upsideGappingSideBySideWhiteLinesCounter = 0
var int downsideGappingSideBySideWhiteLinesCounter = 0
var int bullishKickingCounter = 0
var int bearishKickingCounter = 0

// Llamada a los patrones.
bool isDojiStar = camdPattern.isDojiStarPattern(0)
bool isDragonflyDoji = camdPattern.isDragonflyDojiPattern(0)
bool isLongleggedDoji = camdPattern.isLongleggedDojiPattern(0)
bool isGravestoneDoji = camdPattern.isGravestoneDojiPattern(0)
bool isHammer = camdPattern.isHammerPattern()
bool isInvertedHammer = camdPattern.isInvertedHammerPattern()
bool isHangingMan = camdPattern.isHangingManPattern()
bool isShootingStar = camdPattern.isShootingStarPattern()
bool isBullishBeltHoldLine = camdPattern.isBullishBeltHoldLinePattern()
bool isBearishBeltHoldLine = camdPattern.isBearishBeltHoldLinePattern()
bool isBullishEngulfing = camdPattern.isBullishEngulfingPattern()
bool isBearishEngulfing = camdPattern.isBearishEngulfingPattern()
bool isBullishHarami = camdPattern.isBullishHaramiPattern()
bool isBearishHarami = camdPattern.isBearishHaramiPattern()
bool isHomingPigeon = camdPattern.isHomingPigeonPattern()
bool isThreeIdenticalBlackCrows = camdPattern.isThreeIdenticalBlackCrowsPattern()
bool isBullishCounterAttackLine = camdPattern.isBullishCounterAttackLinePattern()
bool isBearishCounterAttackLine = camdPattern.isBearishCounterAttackLinePattern()
bool isThreeWhiteSoldiers = camdPattern.isThreeWhiteSoldiersPattern()
bool isThreeBlackCrows = camdPattern.isThreeBlackCrowsPattern()
bool isAdvanceBlock = camdPattern.isAdvanceBlockPattern()
bool isDeliberation = camdPattern.isDeliberationPattern()
bool isUniqueThreeRiversBottom = camdPattern.isUniqueThreeRiversBottomPattern()
bool isThreeStarsInTheSouth = camdPattern.isThreeStarsInTheSouthPattern()
bool isBullishBreakaway = camdPattern.isBullishBreakawayPattern()
bool isBearishBreakaway = camdPattern.isBearishBreakawayPattern()
bool isConcealingBabySwallow =  camdPattern.isConcealingBabySwallowPattern()
bool isStickSandwich = camdPattern.isStickSandwichPattern()
bool isMatchingLow = camdPattern.isMatchingLowPattern()
bool isLadderBottom = camdPattern.isLadderBottomPattern()
bool isThrustingLine = camdPattern.isThrustingLinePattern()
bool isInNeck = camdPattern.isInNeckPatter()
bool isOnNeck = camdPattern.isOnNeckPatter()
bool isBullishSeparatingLines = camdPattern.isBullishSeparatingLinesPattern()
bool isBearishSeparatingLines = camdPattern.isBearishSeparatingLinesPattern()
bool isRisingThreeMethods = camdPattern.isRisingThreeMethodsPattern()
bool isFallingThreeMethods = camdPattern.isFallingThreeMethodsPattern()
bool isMatHoldBullish = camdPattern.isMatHoldBullishPattern()
bool isBullishThreeLineStrike = camdPattern.isBullishThreeLineStrikePattern()
bool isBearishThreeLineStrike = camdPattern.isBearishThreeLineStrikePattern()
bool isBullishDojiStar = camdPattern.isBullishDojiStarPattern()
bool isBearishDojiStar = camdPattern.isBearishDojiStarPattern()
bool isMorningStar = camdPattern.isMorningStarPattern()
bool isEveningStar = camdPattern.isEveningStarPattern()
bool isMorningDojiStar = camdPattern.isMorningDojiStarPattern()
bool isEveningDojiStar = camdPattern.isEveningDojiStarPattern()
bool isBullisAbandonedBaby = camdPattern.isBullishAbandonedBabyPattern()
bool isBearisAbandonedBaby = camdPattern.isBearishAbandonedBabyPattern()
bool isBullishTriStar = camdPattern.isBullishTriStarPattern()
bool isBearishTriStar = camdPattern.isBearishTriStarPattern()
bool isUpsideGapTwoCrows = camdPattern.isUpsideGapTwoCrowsPattern()
bool isTwoCrows = camdPattern.isTwoCrowsPattern()
bool isUpsideTasukiGap = camdPattern.isUpsideTasukiGapPattern()
bool isDownsideTasukiGap = camdPattern.isDownsideTasukiGapPattern()
bool isUpsideGapThreeMethods = camdPattern.isUpsideGapThreeMethodsPattern()
bool isDownsideGapThreeMethods = camdPattern.isDownsideGapThreeMethodsPattern()
bool isUpsideGappingSideBySideWhiteLines = camdPattern.isUpsideGappingSideBySideWhiteLinesPattern()
bool isDownsideGappingSideBySideWhiteLines = camdPattern.isDownsideGappingSideBySideWhiteLinesPattern()
bool isBullishKicking  = camdPattern.isBullishKickingPattern()
bool isBearishKicking  = camdPattern.isBearishKickingPattern()

//@function Inserta una etiqueta en el gráfico.
//@param txt El texto de la etiqueta.
//@param color El color de la etiquita.
insertLabel(string txt, color col) =>
    label.new(x = bar_index, y = low, text = txt, style = label.style_label_up, color = col, size = size.normal, yloc = yloc.belowbar)

//@function Imprime la fecha de la vela actual en el log de Pine.
printCandleDate() =>
    log.info("Fecha: {0}-{1}-{2}", dayofmonth(time), month(time), year(time)) 

//@function Incrementa el contador.
//@param counter El contador.
//@returns El contador incrementado.
incrementCounter(int counter) =>
    counter + 1

// Agrego etiqueta del patrón a las velas.
if showPattern
    if isDojiStar and showDojiStar
        insertLabel(camdCONST.getPatternDojiStar(), camdCONST.getColorYellow())
        dojiStarCounter := incrementCounter(dojiStarCounter)
    if isDragonflyDoji and showDragonflyDoji
        insertLabel(camdCONST.getPatternDragonflyDoji(), camdCONST.getColorYellow())
        dragonflyDojiCounter := incrementCounter(dragonflyDojiCounter)
    if isLongleggedDoji and showLongLeggedDoji
        insertLabel(camdCONST.getPatternLongleggedDoji(), camdCONST.getColorYellow())
        longleggedDojiCounter := incrementCounter(longleggedDojiCounter)
    if isGravestoneDoji and showGravestoneDoji
        insertLabel(camdCONST.getPatternGravestoneDoji(), camdCONST.getColorYellow())
        gravestoneDojiCounter := incrementCounter(gravestoneDojiCounter)
    if isHammer and showHammer and showBullishPattern
        insertLabel(camdCONST.getPatternHammer(), camdCONST.getColorLightGreen())
        hammerCounter := incrementCounter(hammerCounter)
    if isInvertedHammer and showInvertedHammer and showBullishPattern
        insertLabel(camdCONST.getPatternInvertedHammer(), camdCONST.getColorLightGreen())
        invertedHamerCounter := incrementCounter(invertedHamerCounter)
    if isHangingMan and showHangingMan and showBearishPattern
        insertLabel(camdCONST.getPatternHangingMan(), camdCONST.getColorLightRed())
        hangingManCounter := incrementCounter(hangingManCounter)
    if isShootingStar and showShootingStar and showBearishPattern
        insertLabel(camdCONST.getPatternShootingStar(), camdCONST.getColorLightRed())
        shootingStarCounter := incrementCounter(shootingStarCounter)
    if isBullishBeltHoldLine and showBullishBeltHoldLine and showBullishPattern
        insertLabel(camdCONST.getPatternBullishBeltHoldLine(), camdCONST.getColorLightGreen())    
        bullishBeltHoldLineCounter := incrementCounter(bullishBeltHoldLineCounter)
    if isBearishBeltHoldLine and showBearishBeltHoldLine and showBearishPattern
        insertLabel(camdCONST.getPatternBearishBeltHoldLine(), camdCONST.getColorLightRed())    
        bearishBeltHoldLineCounter := incrementCounter(bearishBeltHoldLineCounter)
    if isBullishEngulfing and showBullishEngulfing and showBullishPattern
        insertLabel(camdCONST.getPatternBullishEngulfing(), camdCONST.getColorLightGreen())
        bullishEngulfingCounter := incrementCounter(bullishEngulfingCounter)
    if isBearishEngulfing and showBearishEngulfing and showBearishPattern
        insertLabel(camdCONST.getPatternBearishEngulfing(), camdCONST.getColorLightRed())
        bearishEngulfingCounter := incrementCounter(bearishEngulfingCounter)
    if isBullishHarami and showBullishHarami and showBullishPattern
        insertLabel(camdCONST.getPatternBullishHarami(), camdCONST.getColorLightGreen())
        bullishHaramiCounter := incrementCounter(bullishHaramiCounter)
    if isBearishHarami and showBearishHarami and showBearishPattern
        insertLabel(camdCONST.getPatternBearishHarami(), camdCONST.getColorLightRed())
        bearishHaramiCounter := incrementCounter(bearishHaramiCounter)
    if isHomingPigeon and showHomingPigeon and showBullishPattern
        insertLabel(camdCONST.getPatternHomingPigeon(), camdCONST.getColorLightGreen())
        homingPigeonCounter := incrementCounter(homingPigeonCounter)
    if isThreeBlackCrows and showThreeBlackCrows and showBearishPattern
        insertLabel(camdCONST.getPatternThreeBlackCrows(), camdCONST.getColorLightRed())
        threeBlackCrowsCounter := incrementCounter(threeBlackCrowsCounter)
    if isThreeIdenticalBlackCrows and showThreeIdenticalBlackCrows and showBearishPattern
        insertLabel(camdCONST.getPatternThreeIdenticalBlackCrows(), camdCONST.getColorLightRed())
        threeIdenticalBlackCrowsCounter := incrementCounter(threeIdenticalBlackCrowsCounter)
    if isAdvanceBlock and showAdvanceBlock and showBearishPattern
        insertLabel(camdCONST.getPatternAdvanceBlock(), camdCONST.getColorLightRed())
        advanceBlockCounter := incrementCounter(advanceBlockCounter)
    if isDeliberation and showDeliberation and showBearishPattern
        insertLabel(camdCONST.getPatternDeliberation(), camdCONST.getColorLightRed())
        deliberationCounter := incrementCounter(deliberationCounter)
    if isUniqueThreeRiversBottom and showUniqueThreeRiversBottom and showBullishPattern
        insertLabel(camdCONST.getPatternUniqueThreeRiversBottom(), camdCONST.getColorLightGreen())
        uniqueThreeRiversBottomCounter := incrementCounter(uniqueThreeRiversBottomCounter)
    if isThreeStarsInTheSouth and showThreeStarsInTheSouth and showBullishPattern
        insertLabel(camdCONST.getPatternThreeStarsInSouth(), camdCONST.getColorLightGreen())
        threeStarsInTheSouthCounter := incrementCounter(threeStarsInTheSouthCounter)
    if isBullishBreakaway and showBullishBreakaway and showBullishPattern
        insertLabel(camdCONST.getPatternBullishBreakaway(), camdCONST.getColorLightGreen())
        bullishBreakawayCounter := incrementCounter(bullishBreakawayCounter)
    if isBearishBreakaway and showBearishBreakaway and showBearishPattern
        insertLabel(camdCONST.getPatternBearishBreakaway(), camdCONST.getColorLightRed())
        bearishBreakawayCounter := incrementCounter(bearishBreakawayCounter)
    if isConcealingBabySwallow and showConcealingBabySwallow and showBullishPattern
        insertLabel(camdCONST.getPatternConcealingBabySwallow(), camdCONST.getColorLightGreen())
        concealingBabySwallowCounter := incrementCounter(concealingBabySwallowCounter)
    if isStickSandwich and showStickSandwich and showBullishPattern
        insertLabel(camdCONST.getPatternStickSandwich(), camdCONST.getColorLightGreen())
        stickSandwichCounter := incrementCounter(stickSandwichCounter)
    if isMatchingLow and showMatchingLow and showBullishPattern
        insertLabel(camdCONST.getPatternMatchingLow(), camdCONST.getColorLightGreen())
        matchingLowCounter := incrementCounter(matchingLowCounter)
    if isLadderBottom and showLadderBottom and showBullishPattern
        insertLabel(camdCONST.getPatternLadderBottom(), camdCONST.getColorLightGreen())
        ladderBottomCounter := incrementCounter(ladderBottomCounter)
    if isThrustingLine and showThrustingLine and showBearishPattern
        insertLabel(camdCONST.getPatternThrustingLine(), camdCONST.getColorLightRed())
        thrustingLineCounter := incrementCounter(thrustingLineCounter)
    if isInNeck and showInNeck and showBearishPattern
        insertLabel(camdCONST.getPatternInNeck(), camdCONST.getColorLightRed())
        inNeckCounter := incrementCounter(inNeckCounter)
    if isOnNeck and showOnNeck and showBearishPattern
        insertLabel(camdCONST.getPatternOnNeck(), camdCONST.getColorLightRed())
        onNeckCounter := incrementCounter(onNeckCounter)
    if isBullishSeparatingLines and showBullishSeparatingLines and showBullishPattern
        insertLabel(camdCONST.getPatternBullishSeparatingLines(), camdCONST.getColorLightGreen())
        bullishSeparatingLinesCounter := incrementCounter(bullishSeparatingLinesCounter)
    if isBearishSeparatingLines and showBearishSeparatingLines and showBearishPattern
        insertLabel(camdCONST.getPatternBearishSeparatingLines(), camdCONST.getColorLightRed())
        bearishSeparatingLinesCounter := incrementCounter(bearishSeparatingLinesCounter)
    if isRisingThreeMethods and showRisingThreeMethods and showBullishPattern
        insertLabel(camdCONST.getPatternRisingThreeMethods(), camdCONST.getColorLightGreen())
        risingThreeMethodsCounter := incrementCounter(risingThreeMethodsCounter)
    if isFallingThreeMethods and showFallingThreeMethods and showBearishPattern
        insertLabel(camdCONST.getPatternFallingThreeMethods(), camdCONST.getColorLightRed())
        fallingThreeMethodsCounter := incrementCounter(fallingThreeMethodsCounter)
    if isMatHoldBullish and showMatHoldBullish and showBullishPattern
        insertLabel(camdCONST.getPatternMatHoldBullish(), camdCONST.getColorLightGreen())
        matHoldBullishCounter := incrementCounter(matHoldBullishCounter)
    if isBullishThreeLineStrike and showBullishThreeLineStrike and showBullishPattern
        insertLabel(camdCONST.getPatternBullishThreeLineStrike(), camdCONST.getColorLightGreen())
        bullishThreeLineStrikeCounter := incrementCounter(bullishThreeLineStrikeCounter)
    if isBearishThreeLineStrike and showBearishThreeLineStrike and showBearishPattern
        insertLabel(camdCONST.getPatternBearishThreeLineStrike(), camdCONST.getColorLightRed())
        bearishThreeLineStrikeCounter := incrementCounter(bearishThreeLineStrikeCounter)
    if isBullishDojiStar and showBullishDojiStar and showBullishPattern
        insertLabel(camdCONST.getPatternBullishDojiStar(), camdCONST.getColorLightGreen())
        bullishDojiStarCounter := incrementCounter(bullishDojiStarCounter)
    if isThreeWhiteSoldiers and showThreeWhiteSoldiers and showBullishPattern
        insertLabel(camdCONST.getPatternThreeWhiteSoldiers(), camdCONST.getColorLightGreen())
        threeWhiteSoldiersCounter := incrementCounter(threeWhiteSoldiersCounter)
    if isBullishCounterAttackLine and showBullishCounterAttackLine and showBullishPattern
        insertLabel(camdCONST.getPatternBullishCounterAttackLine(), camdCONST.getColorLightGreen())
        bullishCounterAttackLineCounter := incrementCounter(bullishCounterAttackLineCounter)
    if isBearishCounterAttackLine and showBearishCounterAttackLine and showBearishPattern
        insertLabel(camdCONST.getPatternBearishCounterAttackLine(), camdCONST.getColorLightRed())
        bearishCounterAttackLineCounter := incrementCounter(bearishCounterAttackLineCounter)
    if isBearishDojiStar and showBearishDojiStar and showBearishPattern
        insertLabel(camdCONST.getPatternBearishDojiStar(), camdCONST.getColorLightRed())
        bearishDojiStarCounter := incrementCounter(bearishDojiStarCounter)
    if isMorningStar and showMorningStar and showBullishPattern
        insertLabel(camdCONST.getPatternMorningStar(), camdCONST.getColorLightGreen())
        morningStarCounter := incrementCounter(morningStarCounter)
    if isEveningStar and showEveningStar and showBearishPattern
        insertLabel(camdCONST.getPatternEveningStar(), camdCONST.getColorLightRed())
        eveningStarCounter := incrementCounter(eveningStarCounter)
    if isMorningDojiStar and showMorningDojiStar and showBullishPattern
        insertLabel(camdCONST.getPatternMorningDojiStar(), camdCONST.getColorLightGreen())
        morningDojiStarCounter := incrementCounter(morningDojiStarCounter)
    if isEveningDojiStar and showEveningDojiStar and showBearishPattern
        insertLabel(camdCONST.getPatternEveningDojiStar(), camdCONST.getColorLightRed())
        eveningDojiStarCounter := incrementCounter(eveningDojiStarCounter)
    if isBullisAbandonedBaby and showBullishAbandonedBaby and showBullishPattern
        insertLabel(camdCONST.getPatternBullishAbandonedBaby(), camdCONST.getColorLightGreen())
        bullishAbandonedBabyCounter := incrementCounter(bullishAbandonedBabyCounter)
    if isBearisAbandonedBaby and showBearishAbandonedBaby and showBearishPattern
        insertLabel(camdCONST.getPatternBearishAbandonedBaby(), camdCONST.getColorLightRed())
        bearishAbandonedBabyCounter := incrementCounter(bearishAbandonedBabyCounter)
    if isBullishTriStar and showBullishTriStar and showBullishPattern
        insertLabel(camdCONST.getPatternBullishTriStar(), camdCONST.getColorLightGreen())
        bullishTriStarCounter := incrementCounter(bullishTriStarCounter)
    if isBearishTriStar and showBearishTriStar and showBearishPattern
        insertLabel(camdCONST.getPatternBearishTriStar(), camdCONST.getColorLightRed())
        bearishTriStarCounter := incrementCounter(bearishTriStarCounter)
    if isUpsideGapTwoCrows and showUpsideGapTwoCrows and showBearishPattern
        insertLabel(camdCONST.getPatternUpsideGapTwoCrows(), camdCONST.getColorLightRed())
        upsideGapTwoCrowsCounter := incrementCounter(upsideGapTwoCrowsCounter)
    if isTwoCrows and showTwoCrows and showBearishPattern
        insertLabel(camdCONST.getPatternTwoCrows(), camdCONST.getColorLightRed())
        twoCrowsCounter := incrementCounter(twoCrowsCounter)
    if isUpsideTasukiGap and showUpsideTasukiGap and showBullishPattern
        insertLabel(camdCONST.getPatternUpsideTasukiGap(), camdCONST.getColorLightGreen())
        upsideTasukiGapCounter := incrementCounter(upsideTasukiGapCounter)
    if isDownsideTasukiGap and showDownsideTasukiGap and showBearishPattern
        insertLabel(camdCONST.getPatternDownsideTasukiGap(), camdCONST.getColorLightRed())
        downsideTasukiGapCounter := incrementCounter(downsideTasukiGapCounter)
    if isUpsideGapThreeMethods and showUpsideGapThreeMethods and showBullishPattern
        insertLabel(camdCONST.getPatternUpsideGapThreeMethods(), camdCONST.getColorLightGreen())
        upsideGapThreeMethodsCounter := incrementCounter(upsideGapThreeMethodsCounter)
    if isDownsideGapThreeMethods and showDownsideGapThreeMethods and showBearishPattern
        insertLabel(camdCONST.getPatternDownsideGapThreeMethods(), camdCONST.getColorLightRed())
        downsideGapThreeMethodsCounter := incrementCounter(downsideGapThreeMethodsCounter)
    if isUpsideGappingSideBySideWhiteLines and showUpsideGappingSideBySideWhiteLines and showBullishPattern
        insertLabel(camdCONST.getPatternUpsideGappingSideBySideWhiteLines(), camdCONST.getColorLightGreen())
        upsideGappingSideBySideWhiteLinesCounter := incrementCounter(upsideGappingSideBySideWhiteLinesCounter)
    if isDownsideGappingSideBySideWhiteLines and showDownsideGappingSideBySideWhiteLines and showBearishPattern
        insertLabel(camdCONST.getPatternDownsideGappingSideBySideWhiteLines(), camdCONST.getColorLightRed())
        downsideGappingSideBySideWhiteLinesCounter := incrementCounter(downsideGappingSideBySideWhiteLinesCounter)
    if isBullishKicking and showBullishKicking and showBullishPattern
        insertLabel(camdCONST.getPatternBullishKicking(), camdCONST.getColorLightGreen())
        bullishKickingCounter := incrementCounter(bullishKickingCounter)
    if isBearishKicking and showBearishKicking and showBearishPattern
        insertLabel(camdCONST.getPatternBearishKicking(), camdCONST.getColorLightRed())
        bearishKickingCounter := incrementCounter(bearishKickingCounter)

// Indicadores
// Media móvil
float ema14 = na
float ema20 = na
float ema50 = na
float ema200 = na

if showEMA14 == true
    ema14 := ta.ema(source = close, length = 14)
if showEMA20 == true
    ema20 := ta.ema(source = close, length = 20)
if showEMA50 == true
    ema50 := ta.ema(source = close, length = 50)
if showEMA200 == true
    ema200 := ta.ema(source = close, length = 200)

plot(series = ema14, color = camdCONST.getColorLightPurple(), linewidth = 2)
plot(series = ema20, color = camdCONST.getColorYellow(), linewidth = 2)
plot(series = ema50, color = camdCONST.getColorFluorescentBlue(), linewidth = 2)
plot(series = ema200, color = camdCONST.getColorDarkRed(), linewidth = 2)

// Función para verificar si la vela actual está cerca de la EMA de 14
isNearEMA14() =>
    // Calcula la distancia entre el cierre de la vela actual y la EMA de 14
    distance = math.abs(close - ema14)
    // Define un umbral para determinar qué tan cerca queremos que esté la vela
    threshold = ema14 * 0.01 // 1% de la EMA de 14
    // Devuelve verdadero si la distancia es menor que el umbral, indicando que la vela está cerca de la EMA de 14
    distance < threshold

// Llama a la función y dibuja un marcador si la vela está cerca de la EMA de 14
if isNearEMA14() and showBarNearToEMA14
    label.new(x = bar_index, y = high, text = "Cerca de EMA de 14", style=label.style_label_down, color = camdCONST.getColorYellow(), size=size.normal, yloc = yloc.abovebar)

// Maximo historico sin sobre compra.
var float maxCloseRSI = na
float currentRSI = ta.rsi(source = close, length = 14)

if bar_index > 0
    if close > maxCloseRSI and currentRSI < 70 and currentRSI > 30
        maxCloseRSI := close
else
    maxCloseRSI := close

// Variable auxiliar para almacenar el máximo cierre sin sobre compra habilitado/deshabilitado
var float lineValueMaxCloseRSI = na
lineValueMaxCloseRSI := showMaxCloseRSI ? maxCloseRSI : na

plot(series = lineValueMaxCloseRSI, color = camdCONST.getColorDarkGreen(), linewidth = 2, title = "Cierre máximo histórico sin sobre compra")

// Mínimo historico sin sobre venta.
var float minCloseRSI = na

if bar_index > 0
    if close < minCloseRSI and currentRSI < 70 and currentRSI > 30
        minCloseRSI := close
else
    minCloseRSI := close

// Variable auxiliar para almacenar el mínimo cierre sin sobre venta habilitado/deshabilitado
var float lineValueMinCloseRSI = na
lineValueMinCloseRSI := showMinCloseRSI ? minCloseRSI : na

plot(series = lineValueMinCloseRSI, color = camdCONST.getColorDarkRed(), linewidth = 2, title = "Cierre mínimo histórico sin sobre venta")

// Marca en el gráfico cuando el RSI da señala de Compra/Venta.
color rsiColor = na
float rsiCurrVal = ta.rsi(source = close, length = 14)
float rsiPrevVal = ta.rsi(source = close[1], length = 14)

if rsiPrevVal < 30 and rsiCurrVal > 30
    rsiColor := camdCONST.getColorTransparentGreen()
else if rsiPrevVal > 70 and rsiCurrVal < 70
    rsiColor := camdCONST.getColorTransparentRed()

bgcolor(color = rsiColor, title = "RSI Compra/Venta")

